gh-actions: Specify gradle version
Because of:

> Error: Error: Cannot locate a Gradle wrapper properties file at
'/home/runner/work/DigitRecognition/DigitRecognition/gradle/wrapper/gradle-wrapper.properties'.
Specify 'gradle-version' or 'gradle-executable' for projects without
Gradle wrapper configured.